version: "2"
services:
  postgres:
    image: postgres:9.6.11-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tweeter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    networks: 
      - shore
  tweeter:
    image: tweeter:latest
    ports:
      - 8080:4000
    depends_on: 
      - postgres
    container_name: tweeter_web
    networks: 
      - shore
networks:
  shore:
    external: true
